### ISSUE TITLE
script needs to be made multi-arch-aware

### ISSUE THREAD

**Issue by sandrobonazzola** [crobinso/build-fedora-virt-preview#1]
Following up on https://lists.ovirt.org/pipermail/devel/2018-February/032676.html opening this to track adding multi-arch awareness to the build scripts.

**Comment by sharkcz** [comment]
first attempt is at https://github.com/sharkcz/build-fedora-virt-preview/commit/81ee3c796e0518318af11c57f55259255f34ba0d

**Comment by crobinso** [comment]
I've begun work on moving to copr. I have a repo here: https://copr.fedorainfracloud.org/coprs/g/virtmaint-sig/virt-preview/ . Also see the copr-virtpreview script if you're interested

I'll be announcing it and updating the wiki docs before F28 is out. So that means we get ppc64le for free and likely aarch64 soon but who knows beyond that.

So in a way this on its way to being 'fixed' but since the original request was about s390x support I don't expect that will happen soon with this particular repo

**Comment by sharkcz** [comment]
Makes sense, I'll check how we could add s390x into copr. I think it's not a lost case and there is a chance :-)
